name: vector_compass
description: A Flutter app for managing Weaviate vector databases - migrated from React Native Expo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client for API calls (replaces fetch API)
  http: ^1.1.0

  # State management (replaces React hooks)
  provider: ^6.1.1

  # Navigation (replaces expo-router and @react-navigation)
  go_router: ^16.0.0

  # UI components and styling
  cupertino_icons: ^1.0.6

  # Form handling and validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0

  # Loading indicators and progress
  flutter_spinkit: ^5.2.0

  # Alerts and dialogs (replaces Alert from react-native)
  rflutter_alert: ^2.0.7

  # Haptic feedback (replaces expo-haptics)
  haptic_feedback: ^0.5.0

  # Web browser functionality (replaces expo-web-browser)
  url_launcher: ^6.2.2

  # Image handling (replaces expo-image)
  cached_network_image: ^3.3.0

  # Blur effects are built into Flutter with BackdropFilter and ImageFilter
  # No external package needed

  # WebView (replaces react-native-webview)
  webview_flutter: ^4.4.2

  # JSON serialization
  json_annotation: ^4.8.1

  # Shared preferences for local storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules
  flutter_lints: ^6.0.0

  # Code generation for JSON serialization
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true